<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MS" nsURI="MS" nsPrefix="MS">
  <eClassifiers xsi:type="ecore:EClass" name="MService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ontology" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileparameterset" upperBound="-1"
        eType="#//ProfileParameterSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rangeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileParameterSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileparameters" upperBound="-1"
        eType="#//ProfileParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mservice" upperBound="-1"
        eType="#//MService.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileparameterset" upperBound="-1"
        eType="#//ProfileParameterSet.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MService"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileParameterSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceImplementation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mservice" upperBound="-1"
        eType="#//MService.2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileparameterset" upperBound="-1"
        eType="#//ProfileParameterSet.2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodprocess" upperBound="-1"
        eType="#//ProcessType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MService"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileParameterSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceImplementation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ListProcessMethods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MethodsSpecification" upperBound="-1"
        eType="#//MService.3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Strcuture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterProfileSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AttributeSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CapabilitiesSpecefication"
        upperBound="-1" eType="#//MService.3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceSpecefication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InstanceID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Parameters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ValuesSpecefication" upperBound="-1"
        eType="#//MService.3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceHolon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Publish" upperBound="-1"
        eType="#//MServiceProfile.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Implement" upperBound="-1"
        eType="#//MServiceImplementation.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Client" upperBound="-1"
        eType="#//ProductHolon" eOpposite="#//ProductHolon/Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductHolon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Require" eType="#//MServiceSpecefication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" upperBound="-1"
        eType="#//ResourceHolon" eOpposite="#//ResourceHolon/Client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass24"/>
</ecore:EPackage>
